export const ErrorMessages = {
    EmailEmpty: "Please enter your email address.",
    EmailError: 'Please enter a valid email address.',
    PasswordEmpty: "Please enter your password.",
    PasswordError: "Password should be 8 to 16 characters long and include uppercase and lowercase letters, numbers, and special characters.",
    CodeEmpty: "Please enter code.",
    Code1Empty:"Please enter no of family members",
    CodeError: "Invalid OTP. Try again!",
    ChangepasswordEmpty: 'Please enter your password.',
    ChangepasswordError: 'Please enter a valid password.',
    ChangePasswordbelow8: 'Password must contain at least 8 characters.',
    ConfirmPasswordEmpty: 'Please enter your password.',
    ConfirmPasswordMatch: `Password must match.`,
    confirmPasswordForNew: `The confirm password should match the new password.`,
    FullnameError: 'The first name must be at least 2 characters long.',
    firmError:'The firm name or employer name must be at least 2 characters long.',
    designError:"The designation must be at least 2 characters long.",
    FullnameEmpty: 'Please enter your  first name.',
    firmEmpty:"Please enter your firm name or employer name.",
    designEmpty:"Please enter your designation ",
    FullnameError1: "Please enter a valid first name.",
    firmError1: "Please enter a valid firm name or employer name.",
    designError1:"Please enter a valid designation",
   
    mnameError: 'The middle name must be at least 2 characters long.',
    mnameEmpty: 'Please enter your  middle name.',
    mnameError1: "Please enter a valid middle name.",
    snameError: 'The surname must be at least 2 characters long.',
    snameEmpty: 'Please enter your  surname.',
    snameError1: "Please enter a valid surname.",
    CodeLengthError: 'Invalid OTP',
    Code1LengthError:'Invalide No of family members',
    PhoneNumberError: 'Please enter a valid mobile number.',
    PhoneNoEmpty: 'Please enter a mobile number.',
    CityLengthInvalid: "Please enter valid City name.",
    AddressLengthInvalid:"Please enter valid address",
    address1LengthInvalid:"Please enter valid address1",
    talukaLengthInvalid:" Please enter valid Taluka.",
    districtLengthInvalid:"Please enter valid District.",
    stateLengthInvalid:" Please enter  valid State.",
    WhereFromError: "Please select your start location.",
    WhereToError: "Please select your end location.",
    TripDatesError: "Please select trip dates.",
    WrongPassword: "The password is incorrect.",
    TravelError: "Please select travelers.",
    EmptyMessage: 'Please enter your message.',
    MessgaeLength: 'Message should contain at least 8 characters.',
    CategoryError: 'Please add your category.',
};
