export const ErrorMessages = {
    EmailEmpty: "Please enter your email address.",
    EmailError: 'Please enter a valid email address.',
    PasswordEmpty: "Please enter your password.",
    PasswordError: "Password should be 8 to 16 characters long and include uppercase and lowercase letters, numbers, and special characters.",
    CodeEmpty: "Please enter code.",
    CodeError: "Invalid OTP. Try again!",
    ChangepasswordEmpty: 'Please enter your password.',
    ChangepasswordError: 'Please enter a valid password.',
    ChangePasswordbelow8: 'Password must contain at least 8 characters.',
    ConfirmPasswordEmpty: 'Please enter your password.',
    ConfirmPasswordMatch: `Password must match.`,
    confirmPasswordForNew: `The confirm password should match the new password.`,
    FullnameError: 'The name must be at least 2 characters long.',
    FullnameEmpty: 'Please enter your name.',
    FullnameError1: "Please enter a valid name.",
    CodeLengthError: 'Invalid OTP',
    PhoneNumberError: 'Please enter a valid mobile number.',
    PhoneNoEmpty: 'Please enter a mobile number.',
    CityLengthInvalid: "City name should be between 3 and 50 characters.",
    WhereFromError: "Please select your start location.",
    WhereToError: "Please select your end location.",
    TripDatesError: "Please select trip dates.",
    WrongPassword: "The password is incorrect.",
    TravelError: "Please select travelers.",
    EmptyMessage: 'Please enter your message.',
    MessgaeLength: 'Message should contain at least 8 characters.',
    CategoryError: 'Please add your category.',
};
